### ISSUE TITLE
CPS Meter does not work when Attack/Destroy control is set to something else other than click 

### ISSUE THREAD

**Issue by Excigma** [DarkKronicle/KronHUD#2]
**Describe the bug**
When the Attack/Destroy control is changed to something other than clicking, the CPS counter stays at 0
![image](https://user-images.githubusercontent.com/30280397/91247368-449dc880-e7a6-11ea-9eca-95b85d952306.png)

**To Reproduce**
1. Settings > Controls> Attack/Destroy
2. Change the key, see that CPS stays at 0

**Expected behavior**
CPS reflects attacks per second

**Comment by Excigma** [comment]
Pressing Z works correctly for Keystrokes, and triggers the LMB to light up, so a similar click detecting logic could perhaps be implemented 
![image](https://user-images.githubusercontent.com/30280397/91247538-98a8ad00-e7a6-11ea-8cb6-da293dd713ce.png)

**Comment by DarkKronicle** [comment]
Thanks for the bug report. For the keystroke's mod I have implemented that you can change the key and the letter will change, (so if Z is forward, it will show up as Z). The main problem with CPS is the current way I'm doing it is that it only detects clicks with your mouse, not whether or not it is attack/destroy. I did this because it says 'Clicks Per Second', not attacks/blocks placed per second. I will probably add an option to change this behavior.

**Comment by Excigma** [comment]
I'm also having problems with the configuration screen, but I will need to move other mods to another folder to see if there are conflicting mods or anything
![image](https://user-images.githubusercontent.com/30280397/91362736-32c43000-e84f-11ea-8154-7619580eea70.png)

(will probably need it's own issue)

**Comment by DarkKronicle** [comment]
I'm working on that second problem. Will be fixed soon.
